### ISSUE TITLE
Integration - Whats is possible

### ISSUE THREAD

**Issue by lpj145** [cnizzardini/cakephp-swagger-bake#145]
I created plugin a 4 months ago...
https://github.com/lpj145/express-request
basically you can express search parameters to models based on url queries, and, is extremely typed, in some future time, i combine this plugin in another solutions for cake api's like laravel structure, if you have interest, please let me know.

Att Marcos Dantas.

**Comment by cnizzardini** [comment]
I haven't used this, but it looks good. Similar to friendsofcake/search. You can start by trying to integrate it in with the Extension system in your application. If it can be done there I am happy to accept a PR into as an official extension.

See: https://github.com/cnizzardini/cakephp-swagger-bake/tree/develop/src/Lib/Extension

**Comment by cnizzardini** [comment]
I am closing this. If you'd like to build this in as an extension please submit a PR. If you have questions on building an extension feel free to ping me on slack or create an issue.
