### ISSUE TITLE
swagger-bake does not recognise CakePHP installation in a subdirectory 

### ISSUE THREAD

**Issue by iskrenvankov** [cnizzardini/cakephp-swagger-bake#167]
**Description**
I have a CakePHP project in a _cake_ subdirectory of apache's root.
For instance, to access UsersController->index you would go to http://localhost/cake/users.
Now I followed the default installation steps for cakephp-swagger bake and I can see it generated a reasonable-looking swagger.json.
When i go to the route I defined as http://localhost/cake/swagger?doctype=redoc, however, the page is blank and I see an error in the console:

`GET http://localhost/swagger_bake/redoc.standalone.js net::ERR_ABORTED 404 (Not Found)`

The issue seems to be that it's looking for `http://localhost/swagger_bake/` instead of `http://localhost/cake/swagger_bake/`.

**To Reproduce**
1. Install cakephp in _cake_ subdirectory of apache's root
2. Install cakephp-swagger-bake using the default installation steps
3. `bin/cake swagger install`
4. Insert the following in config/routes.php:
```
$routes->scope('/', function (RouteBuilder $builder) {
    $builder->connect('/swagger', ['controller' => 'Swagger', 'action' => 'index', 'plugin' => 'SwaggerBake']);
});
```
5. Go to `http://localhost/cake/swagger?doctype=redoc`
6. Blank screen with console error: `GET http://localhost/swagger_bake/redoc.standalone.js net::ERR_ABORTED 404 (Not Found)`

**Expected behavior**
To see the docs

**Version and Platform (please complete the following information):**
 - OS/Platform: Debian
 - CakePHP: 4.1.2
 - SwaggerBake Version: 1.5.3

**Comment by cnizzardini** [comment]
@iskrenvankov Can you run the console commands and let me know if they work?

https://github.com/cnizzardini/cakephp-swagger-bake#console-commands

Especially `bin/console swagger bake` does that output JSON? Can you load the JSON output into https://editor.swagger.io/ ?

Just trying to make sure the plugin is operating correctly on a basic level before troubleshooting more.

**Comment by cnizzardini** [comment]
If that all pans out try this instead for the swagger controller:

```
$routes->scope('/', function (RouteBuilder $builder) {
    $builder->connect('/swagger', ['controller' => 'Swagger', 'action' => 'index', 'plugin' => 'SwaggerBake']);
});
```

You might also need to adjust some things in your `config/swagger_bake.php`

Let me know the result of all that.

**Comment by iskrenvankov** [comment]
So the two `$routes->scope` suggestions above lead to `Controller class Swagger could not be found.` as an error.
Meanwhile, `bin/cake swagger routes` correctly shows me some routes.
While trying to debug this, a side question appeared: does this bake support non-RESTful routes?
Asking because I defined some custom `$routes->connect()` routes and `bin/cake swagger routes` did not pick them up.

**Comment by cnizzardini** [comment]
No, OpenAPI related tools like swagger and redoc are built for RESTful APIs so this plugin only picks up REST routes: https://book.cakephp.org/4/en/development/rest.html

**Comment by cnizzardini** [comment]
Try modifying these files in vendor. I know this is a no-no, but for validating an issue its fine:

- https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/templates/layout/default.php
- https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/templates/Swagger/index.php

I think the issue is that they all reference /swagger_bake and your setup is /cake/swagger_bake

Let me know if thats the issue, hopefully it is, and we can figure out a solution from there.

**Comment by cnizzardini** [comment]
If thats the case the layout and template files can be altered to accept some optional viewvars, that would be a reasonable addition to the plugin and you'd only have to implement your own Swagger controller as described here: https://github.com/cnizzardini/cakephp-swagger-bake#extending-swaggerbake

**Comment by iskrenvankov** [comment]
Hi,
Manually editing the paths does solve the problem so I would suggest a fix for the plugin itself to pick up automatically the ROOT variable from config/paths.php.
Either way, I've resolved to manual swagger-php annotations to produce the swagger.json file since I'd need some non-CRUD paths in the mix.
Hope this fix would be helpful to someone else with a similar issue though.

**Comment by cnizzardini** [comment]
This supports non-crud paths. You just need to define RESTful routes: https://book.cakephp.org/4/en/development/routing.html#restful-routing

The demo codebase and site have many non-crud route examples: https://github.com/cnizzardini/cakephp-swagger-bake-demo

**Comment by iskrenvankov** [comment]
Oh, I had missed the `$builder->resources()` `map` option in the cakephp documentation for non-crud rest routes, great to know, thanks!

**Comment by cnizzardini** [comment]
For your issue I would just add a Custom controller (https://github.com/cnizzardini/cakephp-swagger-bake#extending-swaggerbake) and reference your own layout and template. I am changing this ticket to just update documentation for this use-case.
