### ISSUE TITLE
SwagForm does not show up

### ISSUE THREAD

**Issue by chyt** [cnizzardini/cakephp-swagger-bake#213]
OS: Mac 15.6, PHP 7.3
Cakephp: 4.1.5
Cakephp-swagger-bake: 1.5.9

I have defined a `POST` action in my Swagger controller, with the following annotation:

```
/**
     * Log in using email/username and password
     * 
     * @Swag\SwagForm(name="username", type="string", description="The username or email address of the user")
     * @Swag\SwagForm(name="password", type="string", description="The plaintext password of the user")
     */
public function loginUsername() { ... }
```

However, when I go to view my Swagger docs, I do not see the description or the form parameters. However for `GET` requests the description and `SwagQuery` both work fine.

Here is an excerpt of my routing code:

```
        $routes->resources('Users', [
            'prefix' => 'Controller',
            'path' => 'users',
            'only' => [
                'login_username',
            ],
            'map' => [
                'login_username' => [
                    'action' => 'login_username',
                    'method' => 'POST',
                ],
            ],
        ]);
```

**Comment by cnizzardini** [comment]
Take a look at the cakephp documentation https://book.cakephp.org/4/en/development/routing.html#mapping-additional-resource-routes. I think your `action` should be `loginUsername`. There is an example of this working on the `v1.5.9` in the demo application https://cakephpswaggerbake.cnizz.com/ (see /examples/form-example).

**Comment by cnizzardini** [comment]
@chyt if that doesn't work, try adding this annotation above your controller action:

```php
@Swag\SwagRequestBody(ignoreCakeSchema=true)
```

**Comment by chyt** [comment]
That seems to have done it. Interestingly the annotations and endpoints still work when using lowercase underscores for the `GET` requests. Thanks for your help!

**Comment by cnizzardini** [comment]
I wonder if I run that through a `strtolower()` call before comparison in area and not the other. Opening this to take a look at it later.
