### ISSUE TITLE
Different summary/description based on request type?

### ISSUE THREAD

**Issue by chyt** [cnizzardini/cakephp-swagger-bake#238]
Is it possible to generate a different summary/description for a method based on each request type? Currently when I specify an array of supported methods (request types) in `routes.php`, they show up in Swagger UI, but they all share the same summary.

**Comment by cnizzardini** [comment]
These should be read in from the Doc Blocks associated with the controller-action. 

https://github.com/cnizzardini/cakephp-swagger-bake#doc-blocks

**Comment by chyt** [comment]
Sorry if my question is unclear, but I don't see where/if my use case is documented. 

The summary is being read in, however I have a method where I want to support `POST`, `GET`, and `DELETE`. However there is only one doc block because it is one method. As a result, the three endpoints that show up in Swagger UI all have the same description. 

I've attached a screenshot for reference, hopefully this is more clear.

**Comment by cnizzardini** [comment]
What do your routes look like?

**Comment by chyt** [comment]
```
        $routes->resources('Alerts', [
            'prefix' => 'Controller',
            'path' => 'alerts',
            'only' => [
                'index',
                'alert',
            ],
            'map' => [
                'alert' => [
                    'action' => 'alert',
                    'method' => ['GET', 'POST', 'DELETE'],
                ],
            ],
        ]);
```

**Comment by cnizzardini** [comment]
In any case, I don't see this library ever supporting that use-case. You can leverage the event system for things like this: https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/docs/extensions.md#swaggerbake-extensions

**Comment by chyt** [comment]
So I'm not very familiar with Swagger, what is the conventional way to do this? Should there be three different methods, each one with a single supported request type?

**Comment by cnizzardini** [comment]
Yes index() = get, add() = post, edit() = patch, delete() = delete. See the demo: https://github.com/cnizzardini/cakephp-swagger-bake-demo

**Comment by cnizzardini** [comment]
I don't advise doing it they you are, but I don't know the requirements of your project either.

**Comment by chyt** [comment]
I see, thanks for this library and the quick response!
