### ISSUE TITLE
@SwagEntityAttribute does not look at the parameter format

### ISSUE THREAD

**Issue by LMG-Jeffy** [cnizzardini/cakephp-swagger-bake#259]
I am having some problems creating the swagger.json automatically. It seems that the *format* field is not included from the enity / table file. The other parameters are correctly converted. Only *Format* is not adopted in the Swagger.JSON file.

File: src/Model/Entity/Vehicle.php
/**
 * Swag\SwagEntityAttribute(name="sales_conditions_warranty_manufacturer_end_date", type="string", format="date-time", description="The date on which the manufacturer warranty on the vehicle expires (only applicable for used vehicles)")
**/

![image](https://user-images.githubusercontent.com/17408698/112151758-df963e00-8be1-11eb-9883-db5edf8bc1b4.png)

cakephp-swagger-bake v 1.6.6
CakePhP 4.2.3

**Comment by cnizzardini** [comment]
Unlikely to resolve but have you tried upgrading to v1.6.8?

**Comment by cnizzardini** [comment]
It's probably because it never gets set here: https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/src/Lib/Schema/SchemaPropertyFromAnnotationFactory.php#L24

**Comment by LMG-Jeffy** [comment]
That is indeed the problem if I add the line `->setFormat($attribute->format ?? ") `  src/Lib/Schema/schemaPropertyFromAnnotationFactory.php it works.

I am using this SwagEntityAttribute because I want to add a description of the field in the Swagger environment.
![image](https://user-images.githubusercontent.com/17408698/112223770-9fa77900-8c2a-11eb-82d4-a940b49f53a7.png)
![image](https://user-images.githubusercontent.com/17408698/112223808-a8984a80-8c2a-11eb-99ff-ff206fb2ef2e.png)

These comments are also in the database at the field, but they are not automatically taken over. Therefore, the use of the SwagEntityAttribute

**Comment by swag** [comment]
I believe I have been added to this mistakenly - please unsubscribe me from
this

**Comment by cnizzardini** [comment]
@LMG-Jeffy I'm on vacation but if you submit a PR I can approve it. Otherwise AFK till Tuesday. 

@swag unsubscribe yourself I can't see how to do it on my phone.  Sorry.
