### ISSUE TITLE
Put endpoint dont show in swagger ui with 'only' parameter

### ISSUE THREAD

**Issue by wiifree** [cnizzardini/cakephp-swagger-bake#312]
I added a resource in routes.php named 'users' with the 'only' parameter to restrict the allowed methods.

`$routes->resources('Users', [
        'only' => ['view', 'edit', 'delete']
]);`

The view and delete methods are shown in the swagger ui with all correct informations but the edit (put) method are ignored. also with the `@Swag\SwagOperation(showPut=true)` annotation.

How i can solve this to show the edit method with put?

**Comment by cnizzardini** [comment]
Put is disabled by default since CakePHP typically does PATCH by default. Using `@Swag\SwagOperation(showPut=true)` should switch PATCH to a PUT. I'll see if I can reproduce any bug sometime this weekend hopefully.

**Comment by wiifree** [comment]
Great, but if you say `@Swag\SwagOperation(showPut=true)` should switch PATCH to PUT this also dont work for me. I added `@Swag\SwagOperation(showPut=true)` on many methods and it replace PATCH with PUT but in a `$routes->resources()` method it display PATCH and PUT together. Perhaps is that another bug.

**Comment by cnizzardini** [comment]
This will not change your actual route definitions, nor should it. This is only for generating OpenAPI. You can change your routes to only allow PUT or PATCH in your `routes.php` config using the `method` key.

https://book.cakephp.org/4/en/development/routing.html#restful-routing

This library does not support defining PUT and PATCH in a single endpoint. The two are different and IMO shouldn't be supported on the same endpoint.
