### ISSUE TITLE
Running in a subfolder

### ISSUE THREAD

**Issue by JulyanoF** [cnizzardini/cakephp-swagger-bake#313]
**Describe the bug**
Is there someway to configure to Swagger UI run in a subpath, like http://localhost/myproject?

**To Reproduce**
Install and configure Swagger bake in a subfolder

**Expected behavior**
Not absolute paths to css and js files

**Attachments**
See screenshots bellow (it's trying to load css and js files to absolute path /swagger_bake/file):
![image](https://user-images.githubusercontent.com/17284704/132874139-aee1f02e-0c81-48de-8408-5c40ef5e17cd.png)
![image](https://user-images.githubusercontent.com/17284704/132874388-a6b2ddfe-0b0e-405f-b9df-b6be2f8bb9b3.png)
![image](https://user-images.githubusercontent.com/17284704/132874416-81051d59-f97c-4874-b27d-529965f59d31.png)

**Comment by cnizzardini** [comment]
You can use your own control and own ui if you prefer: https://github.com/cnizzardini/cakephp-swagger-bake#extending-views-and-controllers

**Comment by cnizzardini** [comment]
This user had a similar question a while back so you may find this helpful: https://github.com/cnizzardini/cakephp-swagger-bake/issues/167

**Comment by JulyanoF** [comment]
I guess it couldn't help too much..

It's running in an Apache (/var/www/html/htdocs/kmm) and apache main folder is /var/www/html and there are many other folders of other projects here. So, my application "default" url is http://localhost/kmm because it's installed at kmm folder

**Comment by JulyanoF** [comment]
I need to change path of .js and .css files of Swagger UI

**Comment by cnizzardini** [comment]
Just build your own template and reference it in your own controller like the docs say. Most of the controller logic is handled in a component so breaking changes are unlikely (but not impossible).
