### ISSUE TITLE
Duplicating parameters

### ISSUE THREAD

**Issue by JulyanoF** [cnizzardini/cakephp-swagger-bake#316]
It's duplicating some attributes when generate swagger.json file:

https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fcakephpswaggerbake.cnizz.com%2Fswagger.json

**Comment by JulyanoF** [comment]
This bug still exists

**Comment by cnizzardini** [comment]
Its been resolved in version 2 which will be getting released soon. 

Is this actually breaking anything? I can probably port the fix into v1. I likely won't be maintaining v1 once v2 goes live unless there is a serious bug.

**Comment by cnizzardini** [comment]
FWIW. I could not find an issue and this "problem" will persist in v2.0.0. I believe its a false positive as it says this schema is invalid:

``yaml
  /actors:
    get:
      operationId: actors:index:get
      summary: List Actors
      description: This example uses the `OpenApiPaginator` attribute to automatically add in page, limit, sort, and direction
      tags:
        - Actors
      externalDocs:
        url: https://github.com/cnizzardini/cakephp-swagger-bake
        description: Check out the documentation
      parameters:
        - $ref: '#/x-swagger-bake/components/parameters/paginatorPage'
        - $ref: '#/x-swagger-bake/components/parameters/paginatorLimit'
        - in: query
          name: sort
          required: false
          schema:
            type: string
            enum:
              - id
              - first_name
              - last_name
              - modified
        - $ref: '#/x-swagger-bake/components/parameters/paginatorDirection'
```
 
Specifically its looking at the `$ref` parameters. I think its a false positive, but if you can determine what https://validator.swagger.io is complaining about I am happy to fix it. @JulyanoF
