### ISSUE TITLE
Feature Request: Merge Swagger.yml and PHP doc block

### ISSUE THREAD

**Issue by bmudda** [cnizzardini/cakephp-swagger-bake#35]
Right now, the definitions in `config/swagger.yml` override the ones in PHP doc block. It will be great to merge those so that documentation based detail can remain in doc block and overrides can be defined in the yml file.

**Comment by cnizzardini** [comment]
So you want SwaggerBake to attempt merging configurations in YML with those in Doc Block? It seems tricky for the library to arbitrarily assume what to keep. Can you provide an example with a YML operation and then doc block and explain with that what the expected outcome would be?

**Comment by bmudda** [comment]
@cnizzardini I meant to say setting the `description` attribute from the PHP doc block if the description key is missing from the YML file. This way we don't have to duplicate large description data from PHP doc block into the swagger yml file and have to maintain it in two places.

**Comment by cnizzardini** [comment]
Okay, I Understand. The Operation `summary` and `description` should be easy. Hopefully the complex types like `parameters`, `responses` etc. are not too bad either.

Do you find yourself running into this issue with Schema?

**Comment by bmudda** [comment]
This came about when I was defining my getToken endpoint which lives under UsersController. But the User schema is more than what is needed for the token endpoint payload (i.e. username and password) and the response is also a just the token and not the whole user object. Therefore I ended up defining it in `swagger.yml` file.  For now duplicating the `description` in the yml and PHP doc block is the main issue I have. But I anticipate wanting to do partial definition in the `swagger.yml` and doing some of it in the PHP doc block as I have several methods where the data it returns or the payload it takes might be a mutated data and not necessarily what is defined in the model schema. But i haven't reached that far yet.

**Comment by cnizzardini** [comment]
Okay I have a very similar use-case to you. I did this instead:

```yaml
components:
    Token:
      type: object
      properties:
        token:
          type: string
```
```php
    /**
     * Login
     *
     * Returns a JSON Web Token (JWT)
     *
     * @see https://jwt.io/
     * @Swag\SwagForm(name="email", type="string", required=true)
     * @Swag\SwagForm(name="password", type="string", required=true)
     * @Swag\SwagResponseSchema(refEntity="#/components/schemas/Token", mimeType="application/json")
     * @throws MethodNotAllowedException
     * @throws UnauthorizedException
     */
    public function token()
```

Side note for `v1.3` I wonder if this will help you down the line: https://github.com/cnizzardini/cakephp-swagger-
bake/issues/37 which implements this sort of stuff: https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

I added that in because I have use-cases where I return a entities with no relations and sometimes return entities with many relations. Think City hasOne Country, I might not always return country. In the coming version 1.3 I can now define something like this:

```
    CityExtended:
      allOf:
        - $ref: '#/components/schemas/City'
        - type: object
          properties:
            country:
              $ref: '#/components/schemas/Country'
```

Then in a method where I want extended information:

```php
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\MethodNotAllowedException When invalid method
     * @Swag\SwagResponseSchema(refEntity="#/components/schemas/CityExtended")
     * @Swag\SwagPaginator()
     */
    public function index()
    {
        $this->request->allowMethod('get');
        $this->paginate = [
            'contain' => ['Countries'],
        ];
        $cities = $this->paginate($this->Cities);

        $this->set(compact('cities'));
        $this->viewBuilder()->setOption('serialize', 'cities');
    }
```

That is all being tested now in the `develop` branch.
