### ISSUE TITLE
Enhance Custom Schema for OpenApiResponse attribute

### ISSUE THREAD

**Issue by wiifree** [cnizzardini/cakephp-swagger-bake#373]
I have been tried to create a OpenApiSchema for my exceptions. I found the field in the docs here https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/docs/attributes.md#openapiresponse to create exception responses, but i think this dont work currently correct. It create a response object with code 500 but in the definition with 404. After that i created a custom exception https://book.cakephp.org/4/en/development/errors.html#creating-your-own-application-exceptions and tried to add a schema for this with #[OpenApiSchema(visibility: OpenApiSchema::VISIBILE_ALWAYS, title: 'My Custom Exception', description: 'My Test description')].
Also i found in the issues the solution https://github.com/cnizzardini/cakephp-swagger-bake/issues/358#issue-1080527204 but i think it should be possible with the PHP attributes system.

After some hours of debugging i found no way to create a custom schema for exception. Did i do something wrong or is this feature currently not possible?

**Comment by cnizzardini** [comment]
Have you tried either of these: https://github.com/cnizzardini/cakephp-swagger-bake#customizing-exception-response-samples

**Comment by wiifree** [comment]
Yeah i tried it and with the @throws tag it worked, but 
- first OpenApiResponse ignore the defined schema of OpenApiExceptionSchemaInterface
- and second i think the implementation of OpenApiExceptionSchemaInterface can also be implemented by attributes e.g. a feature request if it is currently not implemented

**Comment by cnizzardini** [comment]
> I have been tried to create a OpenApiSchema for my exceptions. I found the field in the docs here https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/docs/attributes.md#openapiresponse to create exception responses, but i think this dont work currently correct. It create a response object with code 500 but in the definition with 404. After that i created a custom exception https://book.cakephp.org/4/en/development/errors.html#creating-your-own-application-exceptions and tried to add a schema for this with #[OpenApiSchema(visibility: OpenApiSchema::VISIBILE_ALWAYS, title: 'My Custom Exception', description: 'My Test description')].

[OpenApiSchema](https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/docs/attributes.md#OpenApiSchema) is not meant for exceptions, its meant for use in Entity classes. Exceptions are not entities.

The two ways to add exception schemas to responses are documented and those are the only two ways supported at this time.

> first OpenApiResponse ignore the defined schema of OpenApiExceptionSchemaInterface, i think it is not possible to combine the attribute OpenApiResponse and the class implementation OpenApiExceptionSchemaInterface

Yes, the only way to define a schema for a response with [OpenApiResponse](https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/docs/attributes.md#OpenApiResponse) is using the `ref` option.

> and second i think the implementation of OpenApiExceptionSchemaInterface can also be implemented by attributes e.g. a feature request if it is currently not implemented

Yes you could open a feature request or submit a PR if something is missing.

**Comment by wiifree** [comment]
I dont know what you mean with that i can open a feature request but you could add the enhancement label to this issue ;)

**Comment by cnizzardini** [comment]
What is the problem with the current solutions? Why don't they work for your needs?

**Comment by wiifree** [comment]
The current solution with the OpenApiExceptionSchemaInterface works and i get what i want but i think it's not optimal to implement a interface and 3 static methods only for documentation and not for functionality for the application if features e.g. docblocks and class attributes are available. i think docblocks and attributes are a better place to store with information because you have a better separation between documentation and application functionality.

**Comment by cnizzardini** [comment]
Can you add some pseudo/example code of what a better solution would be?

**Comment by wiifree** [comment]
Sure. Here is my custom NotFoundException with the OpenApiExceptionSchemaInterface implementation:

```
namespace App\Exception;

use Cake\Http\Exception\HttpException;

use SwaggerBake\Lib\OpenApi\Schema;
use SwaggerBake\Lib\OpenApi\SchemaProperty;
use SwaggerBake\Lib\OpenApiExceptionSchemaInterface;


class NotFoundException extends HttpException implements OpenApiExceptionSchemaInterface {

    // Context data is interpolated into this format string.
    protected $_messageTemplate = 'The current %s could not be found.';

    // You can set a default exception code as well.
    protected $_defaultCode = 404;

    public static function getExceptionCode(): string
    {
        return '404';
    }

    
    public static function getExceptionDescription(): ?string
    {
        return 'The current Entity could not be found';
    }

   
    public static function getExceptionSchema(): Schema
    {
        return (new Schema())
            ->setTitle('NotFoundException')
            ->setProperties([
                (new SchemaProperty())->setType('string')->setName('message')->setExample('The current entity could not be found'),
                (new SchemaProperty())->setType('string')->setName('code')->setExample('404')
            ]);
    }

}
```

and i think it would be better if it can be solved by this:

```
namespace App\Exception;

use Cake\Http\Exception\HttpException;

use SwaggerBake\Lib\OpenApi\Schema;
use SwaggerBake\Lib\OpenApi\SchemaProperty;
use SwaggerBake\Lib\OpenApiExceptionSchemaInterface;

#[OpenApiSchema(visbility: OpenApiSchema::VISIBILE_ALWAYS, title: 'Always visible schema')]
#[OpenApiSchemaProperty(name: 'code', default: '404')]
#[OpenApiSchemaProperty(name: 'description', default: 'The current Entity could not be found')]
#[OpenApiSchemaProperty(name: 'message', default: 'The current Entity could not be found')]
class NotFoundException extends HttpException implements OpenApiExceptionSchemaInterface {

    // Context data is interpolated into this format string.
    protected $_messageTemplate = 'The current %s could not be found.';

    // You can set a default exception code as well.
    protected $_defaultCode = 404;

}
```

or what would be even better, you can use the attributes to overwrite, but first the system automatically takes the values ​​from the exception decause the needed values "code", "message" and "title" are in the exception by default with $_defaultCode, $_messageTemplate and class name.

**Comment by cnizzardini** [comment]
I think something like that could work a long with this:

```php
#[OpenApiResponse(statusCode: "404, schema: \App\Exception\NotFoundException::class)]
```

I think it wouldn't be too hard to begin parsing things out of there. I am not sure how well it would handle complex types in there though.

The reason I went with the interface approach is implementing `OpenApiExceptionSchemaInterface::getExceptionSchema` allows you to build complex response examples.

**Comment by cnizzardini** [comment]
You should actually be able to create custom schemas like that for anything, not just exception responses.The library strictly ties itself to cake models for 200 and 201 responses right now.

**Comment by wiifree** [comment]
Sure, `#[OpenApiResponse(statusCode: "404", schema: \App\Exception\NotFoundException::class)]` could work, and with the schema attributes to overwrite some things it solves.

You can also `OpenApiExceptionSchemaInterface::getExceptionSchema` leave implemented for complex responses, and the attributes as an additional option.

If the library currently take cake models for schema i think it can be extended to get schema from exceptions.

**Comment by cnizzardini** [comment]
> You can also `OpenApiExceptionSchemaInterface::getExceptionSchema` leave implemented for complex responses, and the attributes as an additional option.

Yes, nice to give users this control. Will prob create a similar interface for all schema types or recycle that. Will have to see when I get around to this.

> If the library currently take cake models for schema i think it can be extended to get schema from exceptions. Or do you have a different opinion?

Support for converting CakePHP models to OpenAPI schema happens auto-magically. Since an exception is not a model it will be a bit different, but I will suss that out when I get around to this.

**Comment by cnizzardini** [comment]
This has been released  @wiifree  @telemmaite https://github.com/cnizzardini/cakephp-swagger-bake/releases/tag/v2.2.0
