### ISSUE TITLE
DTOs for Response 

### ISSUE THREAD

**Issue by telemmaite** [cnizzardini/cakephp-swagger-bake#376]
It is not a bug report, more like feature request.

Great idea to include: `OpenApiDto`, `OpenApiDtoQuery`, `OpenApiDtoRequestBody` ! But they work only for incomming **Requests**.

Is there a way to do the same for **Responses** ? 
I am calling external API and remapping some fields (using a DTOs) and then directly returning serialized DTOs as **response** from my API. 

For now I have to do double work define my DTORespXs (spatie dtos) then also define  `'#/components/schemas/DTORespX'`

**Comment by cnizzardini** [comment]
This idea popped up in #373 and is being worked on in this PR: #375

**Comment by telemmaite** [comment]
I would say complex. I am making a API/client in front of Looker API.

You can check few example here, but mostly composite collections of  objects.
https://docs.looker.com/reference/api-and-integration/api-reference/v3.1/lookml-model#get_lookml_model_explore

**Comment by cnizzardini** [comment]
For complex stuff I am giving an interface to implement and return full schema as an out, 2.2 will only support scalars. You can comb through whats going on in #375 and provide some feedback if you'd like.

**Comment by telemmaite** [comment]
Thanks sound good and you did really great work! Thank you again.

**Comment by cnizzardini** [comment]
Ty, actually looking at this. I can support both interface and attributes, so you can define scalars using attributes and then still write more complex schema using interface.
