### ISSUE TITLE
Specify Method

### ISSUE THREAD

**Issue by JulyanoF** [cnizzardini/cakephp-swagger-bake#378]
How can I specify method for index (for example)?

I want that index method must be POST type. Is there an annotation in controller that I can specify it?

**Comment by JulyanoF** [comment]
I solved this specifying in routes.php

$builder->resources('PrazoEntrega', [
                'only' => ['index'], 
                'map' => [
                    'index' => [
                        'method' => 'POST',
                        'action' => 'index',
                    ]
                ]
            ]);

**Comment by cnizzardini** [comment]
I guess you figured this out?

**Comment by JulyanoF** [comment]
Yes, but there is another problem. It's forcing to implicit "index" in URL to call that method

![image](https://user-images.githubusercontent.com/17284704/152174484-84c0156d-e999-4258-9254-9bdbfe8ada56.png)

**Comment by JulyanoF** [comment]
I got it using `path`:

```
$builder->resources('PrazoEntrega', [
    'only' => ['index'], 
    'map' => [
        'index' => [
            'method' => 'POST',
            'action' => 'index',
            'path' => ''
        ]
    ]
]);
```
