### ISSUE TITLE
Schema are not generated

### ISSUE THREAD

**Issue by lepresk** [cnizzardini/cakephp-swagger-bake#381]
I created a class and added the `OpenApiSchema` and `OpenApiSchemaProperty` annotations but in the swagger ui my schema is not present.
Getting this error message _`Resolver error at paths./api/v2/products/all.get.responses.200.content.application/json.schema.allOf.0.$ref
Could not resolve reference: Could not resolve pointer: /components/schemas/AdsRessource does not exist in document`_

[Screenshot](https://ibb.co/PG2K0LP)

CakePHP Version: 4.3.4
PHP Version: 8.1.2
Swagger bake version: 2.2

```php
<?php

namespace App\Ressources;

use Cake\Datasource\EntityInterface;
use SwaggerBake\Lib\Attribute\OpenApiSchema;
use SwaggerBake\Lib\Attribute\OpenApiSchemaProperty;

#[OpenApiSchema(visibility: OpenApiSchema::VISIBILE_ALWAYS, title: 'Produit')]
#[OpenApiSchemaProperty(name: 'id', type: 'integer', format: 'int64', description: 'ID')]
#[OpenApiSchemaProperty(name: 'name', type: 'string', description: 'Product name')]
#[OpenApiSchemaProperty(name: 'price', type: 'integer', description: 'Product price')]
#[OpenApiSchemaProperty(name: 'discount_price', type: 'integer', description: 'Product discount price')]
class AdsRessource extends Ressource
{
    /**
     * Serialize method
     * 
     * @param \App\Model\Entity\Annonce $entity
     */
    protected function doSerialize(EntityInterface $entity): array
    {
        return [
            'id' => $entity->id,
            'name' => $entity->name,
            'price' => $entity->price,
            'discount_price' => $entity->prix_promo ?? 0,
            'is_sold' => $entity->is_sold,
            'accept_payment' => $entity->accept_payment,
            'published_at' => $entity->published_at,
            'link' => $entity->link,
            'thumb' => $entity->thumb,
        ];
    }
}
```

Then in my `ProductController.php`
```php
    /**
     * Get all products
     * 
     * @throws \Cake\Http\Exception\NotFoundException when pagination page is incorrect
     */
    #[OpenApiResponse(schemaType: 'array', ref: '#/components/schemas/AdsRessource')]
    public function getAll(): Response
    {
        $query = $this->Annonces->find();

        $query
            ->contain(['Thumb.Medias'])
            ->where($query->newExpr()->gte('Annonces.price', 1000))
            ->where(['Annonces.is_online' => true])
            ->orderDesc('Annonces.published_at');

        $products = $this->paginate($query);
        $products = $products->toArray();

        return $this->success(new AdsRessource($products));
    }
   ```
   
Please clarify if I have do something wrong
![Screenshot](https://user-images.githubusercontent.com/10780686/152339984-78b9c21f-aa97-4e3b-bd46-67b88f0beb91.jpg)

**Comment by cnizzardini** [comment]
Yes:  OpenApiResponse::schema is broken when using schemaType array #380 

This will be fixed in the 2.2.2

**Comment by cnizzardini** [comment]
I just noticed @lepresk that you are using `ref` I think you meant to use `schema`. Read the difference here:

https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/docs/attributes.md#OpenApiResponse

**Comment by lepresk** [comment]
I tried with the full qualified name of the class it doesn't work either
`#[OpenApiResponse(schemaType: 'array', schema: \App\Ressources\AdsRessource::class)]`

**Comment by cnizzardini** [comment]
> I tried with the full qualified name of the class it doesn't work either `#[OpenApiResponse(schemaType: 'array', schema: \App\Ressources\AdsRessource::class)]`

Yes that doesn't work because of a bug that is being worked on. Using `ref` will never though.

**Comment by lepresk** [comment]
> I tried with the full qualified name of the class it doesn't work either `#[OpenApiResponse(schemaType: 'array', schema: \App\Ressources\AdsRessource::class)]`

But I manually declared the schema in the `config\swagger.yam` file, it works, but I lost example preview
![Capture](https://user-images.githubusercontent.com/10780686/152347006-ff6c1a56-c920-4c1e-9934-fb679a526cbb.jpg)

**Comment by cnizzardini** [comment]
Might be another bug haha, i was too hasty in getting this feature out lol. Using `schema` with `schemaType: array` will be released later today. I'll look at this potential `ref` + schemaType: `array` issue later.

**Comment by cnizzardini** [comment]
Closing because of duplicate, but I appreciate the report.

**Comment by cnizzardini** [comment]
@lepresk https://github.com/cnizzardini/cakephp-swagger-bake/releases/tag/v2.2.2
