### ISSUE TITLE
[Bug] OpenApiPaginator attribute generates duplicated "direction" parameters

### ISSUE THREAD

**Issue by JulyanoF** [cnizzardini/cakephp-swagger-bake#394]
OpenApiPaginator attribute generates duplicated "direction" parameters:

![image](https://user-images.githubusercontent.com/17284704/156950665-ca70256d-46d5-4918-8919-9f7809b2876f.png)

I guess it's caused by these two lines from src/Lib/Operation/OperationQueryParameter.php from #345:
![image](https://user-images.githubusercontent.com/17284704/156950776-3cb99e4b-aa6a-4fe7-b090-45bc511d3771.png)

**Comment by cnizzardini** [comment]
Not seeing this in the demo app: https://cakephpswaggerbake.cnizz.com/

Are you just using the attribute? Can you post sample code to reproduce?

**Comment by cnizzardini** [comment]
I was able to reproduce. Looks like you are probably using this code:

```php
#[OpenApiPaginator(useSortTextInput: true)]
```

Please provide sample code in the future.
