### ISSUE TITLE
[Question] Customize CRUD function names

### ISSUE THREAD

**Issue by JulyanoF** [cnizzardini/cakephp-swagger-bake#398]
By default, adding `$builder->resources('Users')` create swagger to following methods:
- index
- view
- add
- edit
- delete

Is it possible to "remap" this function methods for localization? For example, to portuguese (BR):
- listar
- visualizar
- cadastrar
- editar
- excluir

**Comment by cnizzardini** [comment]
Is this something that CakePHP supports?

**Comment by JulyanoF** [comment]
No, I'm talking about swagger generator and not controller generator..
I would like to use these "actions" bellow for other controller methods:
![image](https://user-images.githubusercontent.com/17284704/158064041-9f524246-52a2-480c-bd79-d39f37ec2e05.png)

Specifically, I would like to use "examples" generated for these documentations without make one by one:
![image](https://user-images.githubusercontent.com/17284704/158064078-fc30c952-ba96-4301-80ae-5cbaf1097e82.png)


Other question, I don't know if you could help, but I configurated OpenApiPaginator in index method and it created example above. When I'm debugging, I'm using paginate but not returning paginator objected expected (collection with url, count, total, pages etc):


```php
    #[OpenApiSecurity(name: 'BearerAuth')]
    #[OpenApiPaginator]
    public function index()
    {
        $this->request->allowMethod('get');
        $this->paginate = [
            'contain' => 'Perfis'
        ];
        $usuarios = $this->paginate($this->Usuarios);
        $this->set(compact('usuarios'));
        $this->viewBuilder()->setOption('serialize', 'usuarios');
    }
```

And my return:
![image](https://user-images.githubusercontent.com/17284704/158064201-96d9b089-a244-4531-888b-2b765d8e8edf.png)

**Comment by cnizzardini** [comment]
> No, I'm talking about swagger generator and not controller generator..
> I would like to use these "actions" bellow for other controller methods:

Yes I think I understand. To confirm instead of using `index`:

```php
public function index() {}
```

You want to use `listar`:

```php
public function listar() {}
```

1. Are you currently doing this and mapping them by hand like this: https://book.cakephp.org/4/en/development/routing.html#mapping-additional-resource-routes
2. Are not using the you just using the english action names but wanting to use portuguese action names instead?

Trying to determine where you are in this process and what exactly you need done.

**Comment by cnizzardini** [comment]
> Other question, I don't know if you could help, but I configurated OpenApiPaginator in index method and it created example above. When I'm debugging, I'm using paginate but not returning paginator objected expected (collection with url, count, total, pages etc)

How do you have the paginated data appearing in the sample response? Can you explain how you are getting that in there? I did build this library which does this for you: https://github.com/mixerapi/collection-view

It looks like you might be using that? I'd need to know more information. Are you using that, if not, how are you setting the sample response?

**Comment by cnizzardini** [comment]
Closing due to lack of response.
