### ISSUE TITLE
Plugin controller namespaces not considered when setting FQN 

### ISSUE THREAD

**Issue by aginev** [cnizzardini/cakephp-swagger-bake#399]
**Describe the bug**
I have many Cake plugins with similar structure. Each defining controller with same name like `MainContoller.php` and method `index` in a separate plugin namespace e.g. 

```
app/plugins/PluginOne/src/Controller/Api/MainController.php
app/plugins/PluginTwo/src/Controller/Api/MainController.php
```

`app/plugins/PluginOne/src/Controller/Api/MainController.php` index method has its Swagger attributes but for the `app/plugins/PluginTwo/src/Controller/Api/MainController.php` **no were set**.

Because of the missing plugin namespace when creating the FQN `app/plugins/PluginTwo/src/Controller/Api/MainController.php` get the `app/plugins/PluginOne/src/Controller/Api/MainController.php` attributes.

`bin/cake swagger routes` gives expected results.

**To Reproduce**
1. In a new Cake project create two plugins `PluginOne` and `PluginTwo`
2. Add two plugin controllers both having same name and single method `index`
3. Add Swagger attributes to **just one** of the `index` methods
4. Generate the Swagger docs

**Expected behavior**
Attributes should not be 'inherited' from controller having same name but different namespace.

**Version and Platform (please complete the following information):**
 - macOS Monterey 12.0.1
 - CakePHP: 4.3.6
 - SwaggerBake Version: v2.2.8

**Fix**
https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/src/Lib/Route/RouteScanner.php#L96-L98

```
$path  = $routeDecorator->getPlugin() ? $routeDecorator->getPlugin() . '\\' : '';
$path .= 'Controller\\';
$path .= $routeDecorator->getPrefix() ? $routeDecorator->getPrefix() . '\\' : '';
$path .= $routeDecorator->getController() . 'Controller';
```

If this could be accepted solution of the problem I can send you PR about it.

**Comment by aginev** [comment]
Yes, here it is.

```
return [
    'SwaggerBake' => [
        'prefix' => '/api',
        'yml' => '/config/swagger.yml',
        'json' => '/webroot/swagger.json',
        'webPath' => '/swagger.json',
        'hotReload' => Configure::read('debug'),
        'jsonOptions' => JSON_PRETTY_PRINT,
        'namespaces' => [
            'controllers' => ['\App\\', '\PluginOne\\', '\PluginTwo\\'],
            'entities' => ['\App\\'],
            'tables' => ['\App\\']
        ],
];
```

**Comment by cnizzardini** [comment]
Thanks, I'll see if I can confirm this bug. PRs are always welcomed.

**Comment by cnizzardini** [comment]
I was able to reproduce this, thank you for taking the time to report this and provide an initial solution. I have created #401 which has your solution and another change to separate out plugins using OpenAPI tags. Unfortunately I don't have time today to write any coverage so this PR will take a bit more time until it can be released.
