### ISSUE TITLE
Feature Request: Override default tag attribute

### ISSUE THREAD

**Issue by bmudda** [cnizzardini/cakephp-swagger-bake#42]
Currently, the Controller name is being used for the `tags` attribute. As you suggested, can you please add `@SwagTag(name="myTag")` to override the default?

**Comment by cnizzardini** [comment]
Yes, but will use the existing SwagOperation annotation: `@SwagOperation(tagName="MyTag")`

**Comment by cnizzardini** [comment]
Added @SwagOperation(tagNames=array)

Example:

`@SwagOperation(tagNames={"MyTag","YourTag","OurTag"})`
