### ISSUE TITLE
Support for developers using Windows (those weird guys)

### ISSUE THREAD

**Issue by ArchangelDesign** [cnizzardini/cakephp-swagger-bake#434]
@cnizzardini I'll be submitting a new PR soon to allow me to run unit tests locally on WIndows. Most issues are around paths so that's not a big deal but I'm stuck with 12 tests failing for the same reason
`UnexpectedValueException : You must provide an `$alias` or set the `$defaultTable` property to a non empty string.`

Is there anything I need to set explicitly before those tests pass? This was not an issue on `1.next` btw.

**Comment by cnizzardini** [comment]
Yes. I just fixed that in 2.x, it was introduce in CakePHP 4.4.2. See this PR: https://github.com/cnizzardini/cakephp-swagger-bake/pull/433 and more specifically: https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/src/Lib/Model/ModelScanner.php#L151-L160

**Comment by ArchangelDesign** [comment]
yep, that fixed it, all tests now pass on Windows
