### ISSUE TITLE
Conversion from timestamp to string at swagger bake

### ISSUE THREAD

**Issue by taijane** [cnizzardini/cakephp-swagger-bake#446]
**Problem**
I get an error while generating the swagger.json file with the bake command: "[InvalidArgumentException] Schema type of `timestamp` is invalid. Must be one of: array,boolean,integer,number,object,string". I'm using Mysql 8 and the tables in the database are using the timestamp type which apperently can not be converted to string. 

**Suggestion**
Is it possible to add the **timestamp** type in the **toType()** Method in **src/Lib/Utility/DataTypeConversion.php** to the string conversion? I tested this solution and it worked.

**Comment by cnizzardini** [comment]
What version are you using BTW?

**Comment by cnizzardini** [comment]
See https://github.com/cnizzardini/cakephp-swagger-bake/releases/tag/v1.7.8
