### ISSUE TITLE
[Help] Custom generic response schema

### ISSUE THREAD

**Issue by lepresk** [cnizzardini/cakephp-swagger-bake#447]
Hi, i'm enjoy using this plugin but i'm getting hard time to create custom generic response schema as well.

All of my api response are in this format.

```json
{
  "status": "status string",
  "result": "Response body (can be either object or array)",
  "pagination": {
    "page": 1,
    "current": 1,
    "count": 1,
    "perPage": 50,
    "start": 1,
    "end": 1,
    "prevPage": false,
    "nextPage": true,
    "pageCount": 1
  }
}
```

In my base controller I have created a sniplet that allows me to build the response

```php
class UsersController extends AppController
{
    public function index(): \Cake\Http\Response
    {
        $users = $this->Users->find()->all();
        return $this->success($users);
    }

    public function view($userId): \Cake\Http\Response
    {
        $user = $this->Users->get($userId);
        return $this->success($user);
    }
}
```

```php
class AppController extends Controller
{
    public function success($responseData): \Cake\Http\Response
    {
        $result = [
            'status' => 'OK',
            'result' => $responseData,
        ];
        
        if($this->request->getAttribute('paging') !== null) {
            // Add pagging data to result
        }

        return $this
            ->response
            ->withType('json')
            ->withStringBody(json_encode($result));
    }
}
```

Any ideas of how can i deal with it ?

**Comment by cnizzardini** [comment]
What version are you using?

**Comment by lepresk** [comment]
> What version are you using?

I'm using `2.2.1` version

**Comment by cnizzardini** [comment]
@lepresk did you try this: https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/docs/extensions.md#custom-collection-schemas

> "result": "Response body (can be either object or array)",

Not sure how easy that will be to do with a variable type like that though. Odd API consumer experience IMO too. Why not just always return an array or objects?

**Comment by lepresk** [comment]
This is a constraint imposed by DevOps, I was able to get a result for the collection responses by changing the `x-data-element` path to `result` and `collection` to `pagination`.

Can I do the same thing for responses that do not return a collection?

**Comment by cnizzardini** [comment]
@lepresk there are a few options here: https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/docs/attributes.md#openapiresponse

If that doesn't work give me some specifics.
