### ISSUE TITLE
PHPCS & Doctrine annotations

### ISSUE THREAD

**Issue by ArchangelDesign** [cnizzardini/cakephp-swagger-bake#453]
Not sure what we can do about this, but PHPCS clearly allows
```
'disable: single sniff, docblock, with @'      => [
                'before'         => '/**'.PHP_EOL.' * @phpcs:disable Generic.Commenting.Todo'.PHP_EOL.' */ ',
                'expectedErrors' => 1,
            ],
```
(this is from CS unit tests)
use of `/** @phpcs:disable Something */` while Doctrine Annotation module treats it as missing class. This becomes a problem when you disable `Generic.Files.LineLength.TooLong` within a doc block of a class.
The above results in 
```
Doctrine\Common\Annotations\AnnotationException
[Semantical Error] The annotation "@phpcs:disable" in class App\Model\Entity\EventsUser was never imported. Did you maybe forget to add a "use" statement for this annotation?
```
even if `Hot Reload` is disabled as 
```
/cnizzardini/cakephp-swagger-bake/src/Lib/Swagger.php in SwaggerBake\Lib\Swagger::__construct at line 80
```
always calls
```
        $this->buildSchemasFromModels();
        $this->buildPathsFromRoutes();
```
In my view, all the data should be already written to `swagger.json` when `swagger bake` command runs. Why is there still any code analysis?

**Comment by cnizzardini** [comment]
What version?

**Comment by cnizzardini** [comment]
> always calls

You're right, the constructor is probably doing too much here and should be refactored.

**Comment by cnizzardini** [comment]
However, you lost me on the main problem here. I am confused.

**Comment by ArchangelDesign** [comment]
yeah, I guess it's not clear what the main problem here is. I'll look into this further so I can give you more definitive answer, but at the moment it looks like the library you used (annotations) does not agree with code sniffer. It's not exactly the problem of the library but given the wide use of cs, breaking compatibility with it is rather significant.
If you're suffering the same problem (to whomever reads this) move all cs override commands from doc block to comment block to go around the problem.
@cnizzardini I'll look into potential fixes to this problem. For now this is none-issue, that can be easily resolved (worked around).

**Comment by cnizzardini** [comment]
Okay I understand the problem now, how annoying. I am not sure if there is a way to exclude certain annotations with https://github.com/webmozart/doctrine-common/blob/master/lib/Doctrine/Common/Annotations/AnnotationReader.php, but I bet some try/catch blocks could perhaps handle this in here: https://github.com/cnizzardini/cakephp-swagger-bake/blob/1.next/src/Lib/Utility/AnnotationUtility.php

**Comment by cnizzardini** [comment]
Eh, not possible, but I did find this: https://stackoverflow.com/questions/41496487/how-to-tell-symfony-3-to-ignore-certain-annotations

This worked for me, but I have no idea if it will suppress phpcs internals or not.

```php
/**
 * @IgnoreAnnotation("phpcs:disable")
 */
class OperationsController extends AppController
{
    /**
     * @Swag\SwagOperation(isVisible=false)
     * @phpcs:disable Test ignoring non SwaggerBake namespaces when parsing annotations
     */
    public function isVisible()
    {

    }
}
```
