### ISSUE TITLE
SwaggerBake\Lib\Configuration loads swagger_bake config in a constructor

### ISSUE THREAD

**Issue by segy** [cnizzardini/cakephp-swagger-bake#455]
**Describe the bug**
All of the documentation points out, that you should load a configuration file (https://github.com/cnizzardini/cakephp-swagger-bake#load-the-config). But loading of this file is hardcoded into `SwaggerBake\Lib\Configuration::_construct`.

**Version and Platform (please complete the following information):**
 - SwaggerBake Version: 2.4.3

**Additional context**
The problem is that this file then MUST exist. I'd like to define this in a plugin and not in the main app, but I'm getting error "Could not load configuration file".

**Comment by cnizzardini** [comment]
Ah, I meant to clear this all up a few releases ago but looks like I missed a spot here: https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/src/Lib/Configuration.php#L98

**Comment by cnizzardini** [comment]
https://github.com/cnizzardini/cakephp-swagger-bake/releases/tag/v2.4.4
