### ISSUE TITLE
Feature request: ability to change which connection the model scanner uses

### ISSUE THREAD

**Issue by jamisonbryant** [cnizzardini/cakephp-swagger-bake#461]
**Describe the bug**
Currently the ModelScanner uses the `default` connection and there is no way to override this. In my specific use case, my database is located under the connection name `saas` and `default` is just a throwaway database. When I run `./bin/cake swagger bake` or `./bin/cake swagger model` then I am informed that I have "no" models detected/associated with my routes.

Adding a quick `dd()` to the `ModelScanner::getModelDecorators()` in the try-catch tells me what the problem is:
```shell
'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'throwaway_database.my_model_table' doesn't exist'
```

**To Reproduce**
1. Set up a default database connection
2. Set up a second database connection that actually has some tables
3. Run the model scanner
4. Note that you do not see the tables in the desired database connection in the list of models

**Expected behavior**
We should be able to customize the `connection` on the command level AND ideally at the config level too to account for the hot reload feature.

**Attachments**
N/A

**Version and Platform (please complete the following information):**
 - OS/Platform: MacOS Monterey
 - CakePHP: 4.4.5
 - SwaggerBake Version: v2.4.5

**Additional context**
N/A

**Comment by cnizzardini** [comment]
I knew this day would come.

**Comment by cnizzardini** [comment]
Not sure how many other places this is done: 

https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/src/Lib/Model/ModelScanner.php#L49

But I'd imagine connection could be `swagger_bake` config that defaults to `"default"`. Do you have another way you'd do this @jamisonbryant ?

**Comment by jamisonbryant** [comment]
> I knew this day would come.

Lol, you're welcome! If it helps you feel any better, I am likewise being forced to upgrade all of my own reusable commands on other projects to support multiple connections as well 🎉 

> But I'd imagine connection could be swagger_bake config that defaults to "default". Do you have another way you'd do this @jamisonbryant?

No, I'd pretty much just update the `swagger_bake.php` template as well as your `Configuration` class (which appears to be an object representation of the file) and then the value the user specifies is (I assume) available in the constructor here:
```php
public function __construct(
    private RouteScanner $routeScanner,
    private Configuration $config
) {
}
```

but I don't see any capture of that constructor parameter and use elsewhere in the ModelScanner, only the `Configure::read()` so I'm not sure of its purpose exactly? Wouldn't it make more sense to capture `$this->config` and then do this:
```php
public function getModelDecorators(): array
{
        $return = [];

        $connection = ConnectionManager::get($this->config->getConnectionName());
        $namespaces = $this->config->getNamespaces();
...
```

This is a feature that we sorely need, as we're currently unable to bake any schema on our non-default connection 🙁 let me know if it would be quicker for me to tackle and submit a PR.

**Comment by cnizzardini** [comment]
Yes, that is what I was alluding to. It would require modifying Configuration as well: https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/src/Lib/Configuration.php

**Comment by cnizzardini** [comment]
This should be easy for you to do otherwise I can get to it this weekend.

**Comment by cnizzardini** [comment]
However, maybe see if this solves your problems first: https://discourse.cakephp.org/t/configure-the-default-database-connection-for-the-entire-application/9150

**Comment by jamisonbryant** [comment]
We already considered connection aliasing, and our requirements are we need to maintain both connections for the present.

OK, I'll take a crack at a PR! Thanks @cnizzardini
