### ISSUE TITLE
RouteDecorator doesn't accept `false` as prefix

### ISSUE THREAD

**Issue by ArchangelDesign** [cnizzardini/cakephp-swagger-bake#475]
```
Argument 1 passed to SwaggerBake\Lib\Route\RouteDecorator::setPrefix() must be of the type string or null, bool given, called in /app4/vendor/cnizzardini/cakephp-swagger-bake/src/Lib/Route/RouteDecorator.php on line 81 in /app4/vendor/cnizzardini/cakephp-swagger-bake/src/Lib/Route/RouteDecorator.php on line 250
[TypeError] Argument 1 passed to SwaggerBake\Lib\Route\RouteDecorator::setPrefix() must be of the type string or null, bool given, called in /app4/vendor/cnizzardini/cakephp-swagger-bake/src/Lib/Route/RouteDecorator.php on line 81
```

Is this expected behavior? Cake requires prefix to be `false` otherwise it will be implied during redirection (current prefix will be used), so recently I started explicitly providing prefix as either `string` or `false`. Cake has no problem with that, why do we? :)

**Comment by cnizzardini** [comment]
Hmm, where in CakePHPs documentation does it specify the types that prefix can be?

**Comment by ArchangelDesign** [comment]
good question, I believe I reverse engineered it because it kept the prefix when you redirect from prefixed controller to non-prefix one, in which case it needs to be false, not null. Let me check.

**Comment by ArchangelDesign** [comment]
Perhaps the actual bug is that prefix is preserved? That's why I started providing it in the first place.
running this 
```
$this->redirect(['controller' => 'Users', 'action' => 'twoFactor', 'prefix' => false]);
```
works when you redirect from anywhere, but if you remove `prefix = false` it will not match when you redirect from prefixed to non-prefixed route.
Yeah, those array arguments are annoying but I have Zend Framework 2 background so it's not as bad as 10 years ago 😄 
I'll look into this further and perhaps bother Mark with it. I do believe that `RouteDecorator::prefix` should be `mixed` though. For now I solved it by removing prefixes from routes so it's not urgent, but now I have some more spare time so I might dig into this.

**Comment by cnizzardini** [comment]
Ahh don't bug Mark (yet). I'll open an issue in CakePHP docs.

**Comment by cnizzardini** [comment]
Also can you post a code sample of your routes?

Also what happened when you set the prefix to null? Looking at the code null and boolean likely have the same outcome, but I am not well versed in cakephp internals either.

**Comment by ArchangelDesign** [comment]
```
$builder->get('/error', ['controller' => 'stuff', 'action' => 'stuff', 'prefix' => false);
$builder->get('/error', ['controller' => 'stuff', 'action' => 'stuff', 'prefix' => 'Admin');
```
I think the prefix will default to null here, I'll check it out later.
In `redirect()` method, null doesn't work, it must be `false` otherwise prefix will be inherited.
```
$this->redirect(['controller' => 'name', 'action' => 'stuff', 'prefix' => false);
```

**Comment by cnizzardini** [comment]
Hmm. I haven't tested the library with anything except builder::resource https://book.cakephp.org/4/en/development/routing.html#restful-routing

I thought it ignored non-resource routes.

**Comment by ArchangelDesign** [comment]
hmm, I haven't used resource routes in this project. Json is generated though so looks like they are not ignored.
I'm still using version `v1.7.7`

**Comment by cnizzardini** [comment]
You can submit a PR to the 1.next branch for this. Otherwise I'll get around to it sometime this week.

**Comment by cnizzardini** [comment]
https://github.com/cnizzardini/cakephp-swagger-bake/releases/tag/v1.7.9

**Comment by cnizzardini** [comment]
https://github.com/cnizzardini/cakephp-swagger-bake/releases/tag/v2.4.10
