### ISSUE TITLE
Refactor how controllers are instantiated

### ISSUE THREAD

**Issue by cnizzardini** [cnizzardini/cakephp-swagger-bake#49]
SwaggerBack needs to instantiate controllers for doctrine/annotations to parse `@Swag` annotations and phpdocumentor/reflection-docblock to parse PHP doc blocks.

To do this, SwaggerBake iterates over the namespaces.controllers configuration array until it can find the controller. It does this in a few different places. This kind of hacky. 

It should be possible to use the data in RouteDecorator and the configured route prefix for routes.php to instantiate the class. Scenarios to account for are controllers in:

- [ ] App\Controller
- [ ] Controllers that are part of Userland plugins
- [ ] Controllers that are child namespaces of App\Controller (e.g. namespace App\Controller\Admin)
- [ ] Child namespace in Userland plugins (getting fancy now)

Unit tests don't exist for these scenarios, they will need to be built first before a refactor can begin.
- [ ] App\Controller namespace
- [ ] App\Controller child namespace
- [ ] Plugin\Controller namespace
- [ ] Plugin\Controller child namespace

**Comment by lpj145** [comment]
I'm developer api with prefix, and maybe this don't work yet. :(

**Comment by cnizzardini** [comment]
No, I think it should work. Can you share code in here so we can figure this out? Or DM me on cake slack channel.

**Comment by lpj145** [comment]
![image](https://user-images.githubusercontent.com/11980109/88809108-1b2f5400-d18a-11ea-91ce-22dae0b3c18a.png)
![image](https://user-images.githubusercontent.com/11980109/88809150-26827f80-d18a-11ea-8486-c32fb3fbf530.png)
I try in differents namespaces, but without success but is crazy, the command ``cake swagger routes`` show routes from api.

**Comment by cnizzardini** [comment]
@lpj145 So you have controllers in `App\Controller\Api` or are your controllers just in the standard `App\Controller` namespace?

**Comment by lpj145** [comment]
Yes.. i'm have some questions, have time to talk ? slack or telegram..

**Comment by lpj145** [comment]
```php
<?php
return [
    'SwaggerBake' => [
        'prefix' => '/api',
        'yml' => '/config/swagger.yml',
        'json' => '/webroot/swagger.json',
        'webPath' => '/swagger.json',
        'hotReload' => \Cake\Core\Configure::read('debug'),
        'requestAccepts' => ['application/x-www-form-urlencoded'],
        'responseContentTypes' => ['application/json'],
        'docType' => 'swagger',
        'namespaces' => [
            'controllers' => ['\App\\Controller\\Api'],
            'entities' => ['\App\\'],
            'tables' => ['\App\\']
        ],
    ]
];
```

**Comment by lpj145** [comment]
It is test, i test some probabilities, i have issue with Auth plugin, yes i know, is a poor plugin.

**Comment by cnizzardini** [comment]
You can message be on slack `@cnizzardini` but try this config first:

```php
<?php
return [
    'SwaggerBake' => [
        'prefix' => '/api',
        'yml' => '/config/swagger.yml',
        'json' => '/webroot/swagger.json',
        'webPath' => '/swagger.json',
        'hotReload' => \Cake\Core\Configure::read('debug')
    ]
];
```

**Comment by bmudda** [comment]
@lpj145 I think you need to end your namespace with double back slashes `\\`
```
'controllers' => ['\App\\Controller\\Api\\'],
```

**Comment by lpj145** [comment]
> @lpj145 I think you need to end your namespace with double back slashes `\\`
> 
> ```
> 'controllers' => ['\App\\Controller\\Api\\'],
> ```

i already made it, without success :( i tried a lot of things, tomorrow i inspect code to see whats is wrong.

**Comment by cnizzardini** [comment]
@lpj145 if that does not work then scoped routes (https://book.cakephp.org/3/en/development/routing.html#creating-nested-resource-routes) do not work with SwaggerBake. This should probably be a feature request. I never tested the library against scoped routes, so I am not surprised they don't work.

**Comment by cnizzardini** [comment]
So I tried this use the demo app. This works fine if I leave controllers in the standard `App\Controller` namespace:

```php
    $builder->resources('Countries', function(RouteBuilder $builder){
        $builder->resources('Cities');
    });
```

But once I move the CitiesController into `App\Controller\Countries` things stop working. This was not designed for that setup, mostly because I never setup my code that way, but the library should be made to support this. 

SwaggerBake\Lib\Path\PathFromRouteFactory->create() can't find the controller and so it returns a null Path. I do think this issue can be used to resolve that. It will be put in the `1.6` milestone.

**Comment by lpj145** [comment]
> @lpj145 if that does not work then scoped routes (https://book.cakephp.org/4/en/development/routing.html#creating-nested-resource-routes) do not work with SwaggerBake. This should probably be a feature request. I never tested the library against scoped routes, so I am not surprised they don't work.



> So I tried this using the demo app. This works fine if I leave controllers in the standard `App\Controller` namespace:
> 
> ```
>     $builder->resources('Countries', function(RouteBuilder $builder){
>         $builder->resources('Cities');
>     });
> ```

 Scope don't need another path, prefix yes, because prefix have a convention folder.

> But once I move the CitiesController into `App\Controller\Countries` things stop working. This was not designed for that setup, mostly because I never set up my code that way, but the library should be made to support this.
> 
> SwaggerBake\Lib\Path\PathFromRouteFactory->create() can't find the controller and so it returns a null Path. I do think this issue #49 can be used to resolve that. I will be put it in the `1.6` milestone.

So is not because resources, but is because:
```php
// routes.php file
$routes->prefix('/api', function(RouterBuilder $builder){});
```
This need a convention folder like:
App/Controller/Api

I think error is path of files, he need to get routes.php parse and know where to find controllers classes.

**Comment by cnizzardini** [comment]
As best I can tell when this is called: https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/src/Lib/Path/PathFromRouteFactory.php#L44 its null because of the code in this method:

https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/src/Lib/Utility/NamespaceUtility.php#L33

It's going to be interesting fixing this without introducing a breaking change :-(

**Comment by lpj145** [comment]
😃 yep, i thought some other issue occur, i you see the command `cake swagger routes` see all registered routes it success, why it's only not work in swagger docs ?

**Comment by octisfall** [comment]
I have the same issue.
My controller has namespace App\Controller\Api;
In NamespaceUtility.php you're concat the namespace with 'Controller\\'
![image](https://user-images.githubusercontent.com/19229632/89258266-0a7f5200-d652-11ea-852e-5a0dec2fde16.png)

What if class_exists($entity, true) returns false add another check for class but without concatenation 'Controller\\'?

**Comment by cnizzardini** [comment]
@octisfall Do you want to make that change, test it local, and submit a PR for that? I'm open to doing a 1.5.2 release on that. As long as it works in your app I can help with the unit tests through the PR with you and do some additional testing as well.

**Comment by octisfall** [comment]
@cnizzardini  Sorry, I've decided to go with pure openapi file for now. Your plugin looks promising I would even come back to it after some time. Thanks for your effort!

**Comment by lpj145** [comment]
> @cnizzardini Sorry, I've decided to go with pure openapi file for now. Your plugin looks promising I would even come back to it after some time. Thanks for your effort!

i can solve this issue by: using `scope` function instead of `prefix`  maintain files in *controller/* folder, yes i know is a miss conception, but, solve my problem for this moment, at this time, i'm working project with few time to finish, but in future, i can contribute with this package.

**Comment by cnizzardini** [comment]
Maybe try what @lpj145 said @octisfall

**Comment by chyt** [comment]
I believe I'm experiencing a similar issue (not able to reference a controller in a child namespace) and came up with a solution based on what @octisfall said about appending `Controller`. 

In my situation, my Swagger prefix is `/mobile`, namespace is `App/Controller/Mobile` and I want to route a resource `Listings` at `App/Controller/Mobile/ListingsController.php` to `/mobile/listings`. 

First, I created a new namespace at `App/Controller/Mobile/Controller` and moved the `ListingsController` to that new namespace.

Next, in `swagger_bake.php`, I set the namespace to be `App/Controller/Mobile`, understanding that `Controller` would automatically be appended. 

Finally, in my `/mobile` route, I set this:

```
$routes->resources('Listings', [
            'prefix' => 'Controller'
]);
```

such that it would reference the `Listings` controller in the `Controller` child namespace. 

In this way I'm still able to have all my API endpoints in a separate child namespace, it just involves some minor inconvenience to create a new sub-namespace called `Controller`.

**Comment by cnizzardini** [comment]
Okay, I didn't realize so many people used CakePHP like this. I've personally never used sub-folders in Controller namespaces, but it appears plenty others do. This is slated for the next release.

**Comment by lpj145** [comment]
@cnizzardini if you pretend to adjust this issue, yes many people take that way, because a lot of cake applications going to api, but, in another way, cake is changing some core functionalities and thought if you solve this problem based on routes you can go in trouble, i think the best way to plugin analyze and mount endpoints routes, is based on configuration of swagger_bake pointing to one o multiples locations of controllers.

**Comment by cnizzardini** [comment]
@lpj145 @octisfall @chyt I would not do ugly hacks in your application as a result of this bug. I should have a release ready by the end of the week that resolves this.

**Comment by cnizzardini** [comment]
@lpj145 @octisfall @chyt there is a patch for this no setting in the master branch. If you can test this on your projects locally that would be great. `composer require --no-cache cnizzardini/cakephp-swagger-bake:dev-master`

If that checks out I can do a 1.5.2 release.

**Comment by cnizzardini** [comment]
I tested this a bit more today and it works for restful sub-resources:

```php
    $builder->resources('Countries', function(RouteBuilder $builder){
        $builder->resources('Cities');
    });
```

Which outputs routes like this: `/countries/:country_id/cities`

I then tested what you all appear to be doing with a namespace like `App\Controller\Sub\LanguagesController`:

```php
$builder->resources('Languages', ['path' => 'sub/languages', 'prefix' => 'Sub']);
```

And this is successful as well: `/sub/languages`

I'd prefer you all tested this still, but if not I'll deploy a 1.5.2 sometime in the next day or two.

**Comment by chyt** [comment]
Doesn't seem to be working for me with the removal of the `Controller` prefix. When I do that, I don't see the endpoints showing up in the Swagger docs anymore.

**Comment by cnizzardini** [comment]
Can you double-check that you are on dev-master branch e38b8de @chyt 

If you are on that commit, can you post the the route from your routes.php. Also run bin/cake swagger routes and see it its in there.

**Comment by cnizzardini** [comment]
As best I can tell this is resolved. See https://github.com/cnizzardini/cakephp-swagger-bake-demo and live demo https://cakephpswaggerbake.cnizz.com/
