### ISSUE TITLE
PHP8.2 - deprecation warning when setting dynamic properties on OpenApi\Schema

### ISSUE THREAD

**Issue by jamisonbryant** [cnizzardini/cakephp-swagger-bake#500]
**Describe the bug**
`Deprecated (8192) : Creation of dynamic property SwaggerBake\Lib\OpenApi\Schema::$x-data-element is deprecated [in /opt/bitnami/vhosts/api-v4/vendor/cnizzardini/cakephp-swagger-bake/src/Lib/OpenApi/Schema.php, line 116]`

**To Reproduce**
1. Run a PHP8.2 server
2. Run swagger bake
3. Load up the swagger docs in a browser

**Expected behavior**
No deprecation error is thrown because the Schema class appropriately handles dynamic properties in PHP8.2.

**Attachments**
N/A don't think it's relevant

**Version and Platform (please complete the following information):**
 - OS/Platform: Debian GNU/Linux 11 (bullseye)
 - CakePHP: 4.4.8
 - SwaggerBake Version: 2.5.1

**Additional context**
From what I can tell, the Schema class is 100% meant to have dynamic properties, which if I'm correct is a good thing because there's a clear and easy fix, which is to add the trait `#[AllowDynamicProperties]`. However, I think another solution could be to implement the `__get()` and `__set()` methods [as shown here](https://stitcher.io/blog/deprecated-dynamic-properties-in-php-82) and read/write `$this->properties` accordingly.

I checked `composer.json` and it looks like PHP8.0+ is supported, so is it feasible to fix this? I know PHP8.2 is kinda new but I'm using a Bitnami LAMP image that I can't downgrade PHP on without destroying and rebuilding the whole server 🙄 .

**Comment by cnizzardini** [comment]
Seems like `#[AllowDynamicProperties]` is the easiest solution for now. You can submit a PR for this or wait for me to get around to it.

**Comment by jamisonbryant** [comment]
I experimented for a little and, oddly enough, adding the trait didn't seem to have any effect. I don't know if I was adding it to the right class or not...? 🤔 

It's just a deprecation warning, though, and I'm on a deadline so I just turned off debug mode and that makes it go away. I will (gratefully) wait for the next patch version for this fix.

**Comment by jamisonbryant** [comment]
Update: I figured out what I was doing wrong with the trait and made a PR. Take a look when available, thanks!

**Comment by cnizzardini** [comment]
https://github.com/cnizzardini/cakephp-swagger-bake/releases/tag/v2.5.2
