### ISSUE TITLE
SwaggerBake config namespace is null in Configuration constructor

### ISSUE THREAD

**Issue by jamisonbryant** [cnizzardini/cakephp-swagger-bake#505]
**Describe the bug**
I was running the by-the-book fresh install of MixerAPI and I discovered a bug (I think) in SwaggerBake:
```
array_key_exists(): Argument #2 ($array) must be of type array, null given
```
it didn't take much digging to find these lines:
```
// src/Lib/Configuration.php
public function __construct(array $config = [], string $root = ROOT)
{
    $this->root = $root;
    $config = !empty($config) ? $config : Configure::read('SwaggerBake');       // problem is on this line

    foreach (['yml', 'json', 'webPath', 'prefix'] as $property) {
    ...
}
```

I think something is not right with `bin/cake mixerapi install` because it did not modify my bootstrap.php to add the `Configure::load()` call for the baked swagger_bake.php config file, and so that's why the namespace is empty here (LMK if you want me to file a separate ticket for this @cnizzardini).

The solution (IMO) is simple, change the `Configure::read(...)` to `Configure::readOrFail(...)`. This turns the above error into:
```
Expected configuration key "SwaggerBake" not found.
```
which is a much more useful error message as it indicates what the problem truly is.

**To Reproduce**
1. `composer require mixerapi/mixerapi`
2. `bin/cake plugin install MixerApi`
3. `bin/cake mixerapi install`
4. Load up <http://localhost> in a browser

**Expected behavior**
If for some reason my SwaggerBake config is not available when this constructor is called, crash with a meaningful error message instead of an array_key_exists/TypeError mishmash.

**Attachments**
N/A

**Version and Platform (please complete the following information):**
 - OS/Platform: Windows 10 using Docker on WSL
 - CakePHP: 4.4.10
 - SwaggerBake Version: 2.5.2 (*clarification: so far I have only manually installed `mixerapi/mixerapi@1.1.7` in this project, so this version of SwaggerBake is whatever comes with the MixerAPI version I'm using)

**Additional context**

**Comment by robitmoh** [comment]
Same error
https://mixerapi.com/plugins/cakephp-swagger-bake/#installation

> Load the config
> 
> In your config/bootstrap.php file:
> 
> Configure::load('swagger_bake', 'default', false);
>

**Comment by cnizzardini** [comment]
https://github.com/mixerapi/mixerapi-dev/issues/140

**Comment by cnizzardini** [comment]
I see, there is still room for improvement in this lib @jamisonbryant

**Comment by cnizzardini** [comment]
https://github.com/cnizzardini/cakephp-swagger-bake/releases/tag/v2.5.3
