### ISSUE TITLE
Logic of Configuration class

### ISSUE THREAD

**Issue by segy** [cnizzardini/cakephp-swagger-bake#513]
I have a question about the Configuration file. I wanted to modify template / layout for the swagger. It seemed logical to me to extend the `SwaggerBake\Lib\Configuration` and modify `getLayout` and `getView` methods.

But at least I need to copy all the private properties. Otherwise it fails in the constructor with "Property X does not exist in class" message. 

Would it be OK for you to change these properties to protected?

**Comment by segy** [comment]
The second thing. I'd suggest changing the code here: https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/src/Lib/Service/OpenApiControllerService.php the way, that the `Configuration` (possibly passed as the first parameter) will be passed to the constructor of `SwaggerFactory`. Do you agree?

**Comment by cnizzardini** [comment]
> The second thing. I'd suggest changing the code here: https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/src/Lib/Service/OpenApiControllerService.php the way, that the `Configuration` (possibly passed as the first parameter) will be passed to the constructor of `SwaggerFactory`. Do you agree?

I agree here.

**Comment by segy** [comment]
> On the first item, did you try this: https://github.com/cnizzardini/cakephp-swagger-bake#extending-views-and-controllers
> 
> So you should just be able to create a `templates/plugin/SwaggerBake` directory and add the templates in there. Is there a reason to not use this approach?

I know, but I'd like to do this in another plugin, and I'm not sure, how this does work. Otherwise you can probably need to change any other behavior of the Configuration class and this problem will still be there, so seems logical to me to change these properties to protected. If not, than probably do some other logic for processing the configuration. What do you think?

**Comment by cnizzardini** [comment]
I do wonder if its better to create a ConfigurationInterface and leave the current as is. This would require changing some arg signatures and I don't know if it will actually solve your issue. In general, I don't like extension.

**Comment by cnizzardini** [comment]
Also, curious why you cannot use setters?

**Comment by segy** [comment]
but this a feature in the constructor. so you pass no config, it fetches from SwaggerBake config and then sets the properties (and fails as described above). How would you change this to use setters?

**Comment by cnizzardini** [comment]
It could accept `ConfigurationInterface`, which would be implemented by an optional `ConfigurationImplementationTrait` and then you would pass in your own instance of `ConfigurationInterface` which would do your things.

It's a bit more work than I want to do on this library though since I am mainly hoping to just do minor things outside of maintaining compatibility with cake, php, and openapi.

**Comment by cnizzardini** [comment]
https://github.com/cnizzardini/cakephp-swagger-bake/releases/tag/v2.5.5

**Comment by segy** [comment]
I understand, but still... this is much more simple to extend the class so why make it "nicer" but harder. Thanks for merging it!
