### ISSUE TITLE
Feature Query: is it possible to hide model properties?

### ISSUE THREAD

**Issue by TheGlenn88** [cnizzardini/cakephp-swagger-bake#518]
Say we have a User model that has some fields like
name
email
flagged_as_spam

is it possible to hide the field `flagged_as_spam` from the OpenAPI documentation? I can't seem to see a `isVisible` property on `OpenApiSchemaProperty`, wondering if there is another way.

**Comment by TheGlenn88** [comment]
Thanks for the reply, unfortunately I cannot use the `$_hidden` property on the entity as that will hide them for all endpoints that use the User Entity for example.

Imagine a /users endpoint designed for viewing by the end-user and a /users endpoint for an admin. Realistically I only want to document the end-user endpoint missing some extra properties hidden.

still trying to get the hang of this package, it's really nice so far.

**Comment by cnizzardini** [comment]
I guess you are not returning the full entity then on these "custom" end-user endpoints, I think both of these options will work for you:

1. You can use the `OpenApiResponse` attribute, either specifying custom OpenAPI YAML or using a response DTO, both examples are documented here: https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/docs/attributes.md#openapiresponse
2. You can use an event listener to modify the response for a specific endpoint: https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/docs/events.md

**Comment by cnizzardini** [comment]
Closing due to lack of response
