### ISSUE TITLE
collection generation

### ISSUE THREAD

**Issue by MasaKni** [cnizzardini/cakephp-swagger-bake#526]
when updating to cakephp 5 pagination now returns PaginatedResultSet not ResultSet, so need to update the code.

**Comment by cnizzardini** [comment]
Can you be more specific with what error you are getting? Have you tried with this branch: https://github.com/cnizzardini/cakephp-swagger-bake/tree/v3.0.0

It should be compatible with cakephp 5, but I will not release until after cakephp 5 is released, period.

**Comment by MasaKni** [comment]
since cakephp 5 does not use requestHandler anymore then setting the CollectionView now in mixerapi/collection-view using RequestHandler is deprecated.

**Comment by cnizzardini** [comment]
Okay, that is a different plugin. All mixerapi issues should be created here: https://github.com/mixerapi/mixerapi-dev/

There is an active branch/pr in there already for cake5. I intend on having that done by end of the year.
