### ISSUE TITLE
 Undefined array key "securitySchemes"  in Cakaphp 4.15 version 

### ISSUE THREAD

**Issue by shaan100** [cnizzardini/cakephp-swagger-bake#528]
I have get this error after install this plugin. 
![Screenshot from 2023-07-21 09-50-17](https://github.com/cnizzardini/cakephp-swagger-bake/assets/105695000/513b0614-4446-42c4-b267-3c2f35edf09b)

[Warning (2) ](javascript:void(0);): Undefined array key "securitySchemes" [in /var/www/html/dp/vendor/cnizzardini/cakephp-swagger-bake/src/Lib/Operation/OperationSecurity.php, line 97]
[Warning (512) ](javascript:void(0);): Unable to emit headers. Headers sent in file=/var/www/html/dp/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php line=36 [in /var/www/html/dp/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 71]
[Warning (2) ](javascript:void(0);): Cannot modify header information - headers already sent by (output started at /var/www/html/dp/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php:36) [in /var/www/html/dp/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 164]
[Warning (2) ](javascript:void(0);): Cannot modify header information - headers already sent by (output started at /var/www/html/dp/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php:36) [in /var/www/html/dp/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 197]
[Warning (2) ](javascript:void(0);): Cannot modify header information - headers already sent by (output started at /var/www/html/dp/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php:36) [in /var/www/html/dp/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 197]{ "exception": "TypeError", "message": "count(): Argument #1 ($value) must be of type Countable|array, null given", "url": "\/api", "code": 500, "error": {}, "exceptions": [ {} ], "trace": [ { "file": "\/var\/www\/html\/dp\/vendor\/cnizzardini\/cakephp-swagger-bake\/src\/Lib\/Operation\/OperationSecurity.php", "line": 97 }, { "file": "\/var\/www\/html\/dp\/vendor\/cnizzardini\/cakephp-swagger-bake\/src\/Lib\/Operation\/OperationSecurity.php", "line": 97, "function": "count" }, { "file": "\/var\/www\/html\/dp\/vendor\/cnizzardini\/cakephp-swagger-bake\/src\/Lib\/Operation\/OperationSecurity.php", "line": 56, "function": "assignAuthenticationComponent", "class": "SwaggerBake\\Lib\\Operation\\OperationSecurity", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cnizzardini\/cakephp-swagger-bake\/src\/Lib\/Operation\/OperationFromRouteFactory.php", "line": 81, "function": "getOperationWithSecurity", "class": "SwaggerBake\\Lib\\Operation\\OperationSecurity", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cnizzardini\/cakephp-swagger-bake\/src\/Lib\/Swagger.php", "line": 219, "function": "create", "class": "SwaggerBake\\Lib\\Operation\\OperationFromRouteFactory", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cnizzardini\/cakephp-swagger-bake\/src\/Lib\/Swagger.php", "line": 43, "function": "buildPathsFromRoutes", "class": "SwaggerBake\\Lib\\Swagger", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cnizzardini\/cakephp-swagger-bake\/src\/Lib\/Factory\/SwaggerFactory.php", "line": 48, "function": "__construct", "class": "SwaggerBake\\Lib\\Swagger", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cnizzardini\/cakephp-swagger-bake\/src\/Controller\/Component\/SwaggerUiComponent.php", "line": 31, "function": "create", "class": "SwaggerBake\\Lib\\Factory\\SwaggerFactory", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Controller\/ComponentRegistry.php", "line": 133, "function": "__construct", "class": "SwaggerBake\\Controller\\Component\\SwaggerUiComponent", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Core\/ObjectRegistry.php", "line": 110, "function": "_create", "class": "Cake\\Controller\\ComponentRegistry", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Controller\/Controller.php", "line": 304, "function": "load", "class": "Cake\\Core\\ObjectRegistry", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cnizzardini\/cakephp-swagger-bake\/src\/Controller\/SwaggerController.php", "line": 17, "function": "loadComponent", "class": "Cake\\Controller\\Controller", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Controller\/Controller.php", "line": 229, "function": "initialize", "class": "SwaggerBake\\Controller\\SwaggerController", "type": "-\u003E" }, { "function": "__construct", "class": "Cake\\Controller\\Controller", "type": "-\u003E", "file": "[internal]", "line": "??" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Controller\/ControllerFactory.php", "line": 87, "function": "newInstance", "class": "ReflectionClass", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/BaseApplication.php", "line": 318, "function": "create", "class": "Cake\\Controller\\ControllerFactory", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php", "line": 86, "function": "handle", "class": "Cake\\Http\\BaseApplication", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/Middleware\/CsrfProtectionMiddleware.php", "line": 174, "function": "handle", "class": "Cake\\Http\\Runner", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php", "line": 82, "function": "process", "class": "Cake\\Http\\Middleware\\CsrfProtectionMiddleware", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/Middleware\/BodyParserMiddleware.php", "line": 157, "function": "handle", "class": "Cake\\Http\\Runner", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php", "line": 82, "function": "process", "class": "Cake\\Http\\Middleware\\BodyParserMiddleware", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/authorization\/src\/Middleware\/RequestAuthorizationMiddleware.php", "line": 110, "function": "handle", "class": "Cake\\Http\\Runner", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php", "line": 82, "function": "process", "class": "Authorization\\Middleware\\RequestAuthorizationMiddleware", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/authorization\/src\/Middleware\/AuthorizationMiddleware.php", "line": 129, "function": "handle", "class": "Cake\\Http\\Runner", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php", "line": 82, "function": "process", "class": "Authorization\\Middleware\\AuthorizationMiddleware", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/authentication\/src\/Middleware\/AuthenticationMiddleware.php", "line": 124, "function": "handle", "class": "Cake\\Http\\Runner", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php", "line": 82, "function": "process", "class": "Authentication\\Middleware\\AuthenticationMiddleware", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Routing\/Middleware\/RoutingMiddleware.php", "line": 186, "function": "handle", "class": "Cake\\Http\\Runner", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php", "line": 82, "function": "process", "class": "Cake\\Routing\\Middleware\\RoutingMiddleware", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Routing\/Middleware\/AssetMiddleware.php", "line": 68, "function": "handle", "class": "Cake\\Http\\Runner", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php", "line": 82, "function": "process", "class": "Cake\\Routing\\Middleware\\AssetMiddleware", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Error\/Middleware\/ErrorHandlerMiddleware.php", "line": 131, "function": "handle", "class": "Cake\\Http\\Runner", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php", "line": 82, "function": "process", "class": "Cake\\Error\\Middleware\\ErrorHandlerMiddleware", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/debug_kit\/src\/Middleware\/DebugKitMiddleware.php", "line": 60, "function": "handle", "class": "Cake\\Http\\Runner", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php", "line": 82, "function": "process", "class": "DebugKit\\Middleware\\DebugKitMiddleware", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php", "line": 67, "function": "handle", "class": "Cake\\Http\\Runner", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/vendor\/cakephp\/cakephp\/src\/Http\/Server.php", "line": 90, "function": "run", "class": "Cake\\Http\\Runner", "type": "-\u003E" }, { "file": "\/var\/www\/html\/dp\/webroot\/index.php", "line": 40, "function": "run", "class": "Cake\\Http\\Server", "type": "-\u003E" } ], "file": "\/var\/www\/html\/dp\/vendor\/cnizzardini\/cakephp-swagger-bake\/src\/Lib\/Operation\/OperationSecurity.php", "line": 97 }

**Comment by cnizzardini** [comment]
You're in version 1.x I am guessing? Can you try adding a securityScheme to see if this error goes away?

https://swagger.io/docs/specification/authentication/
