### ISSUE TITLE
 Undefined array key "securitySchemes"

### ISSUE THREAD

**Issue by shaan100** [cnizzardini/cakephp-swagger-bake#529]
i am using this plugin "cnizzardini/cakephp-swagger-bake": "^1.4", and it show error please check below image. I am currently working on Cakephp 4.4.17

![Screenshot from 2023-08-22 21-40-19](https://github.com/cnizzardini/cakephp-swagger-bake/assets/105695000/73a1698b-2006-4d32-b986-f178dbf5ed9b)

**Comment by cnizzardini** [comment]
What version of this library are you running?

**Comment by shaan100** [comment]
I run this command composer show -i | grep swagger and got follow response please see in below

You are using the deprecated option "installed". Only installed packages are shown by default now. The --all option can be used to show all packages.
cnizzardini/cakephp-swagger-bake               v1.4.0  Automatically generate Swagger documentation from your exist routes with minimal comments and configuration

**Comment by cnizzardini** [comment]
Can you check your composer.lock for the exact version you are using or just run `composer update cnizzardini/cakephp-swagger-bake`. 

I am trying to confirm you are on the latest version of the library.  Your `composer.json` only gives a version constraint, but that doesn't tell me the exact version number you are on.

**Comment by shaan100** [comment]
"name": "cnizzardini/cakephp-swagger-bake",
            "version": "v1.4.0",
            "source": {
                "type": "git",
                "url": "https://github.com/cnizzardini/cakephp-swagger-bake.git",
                "reference": "3077ad0fa2473ca6c18c5f18eaefdade1a9d8d19"
            },

**Comment by shaan100** [comment]
yes i am using latest version cakephp 4.4.17 and swagger plugin

**Comment by shaan100** [comment]
![Screenshot from 2023-09-02 20-56-56](https://github.com/cnizzardini/cakephp-swagger-bake/assets/105695000/91266a19-154f-40dc-a5c3-4596511606ab)

**Comment by cnizzardini** [comment]
Your composer lock says you are on version 1.4.0. The latest version of 1.x which is [v1.7.11](https://github.com/cnizzardini/cakephp-swagger-bake/releases/tag/v1.7.11) has likely resolved this issue: 

https://github.com/cnizzardini/cakephp-swagger-bake/blob/1.next/src/Lib/Operation/OperationSecurity.php

Verify you have upgraded to the latest version.

**Comment by shaan100** [comment]
I do not know what exactly problem man, just update composer and composer update cnizzardini/cakephp-swagger-bake but still getting error on screen.

please tell me how can i update?
composer update this command return nothing update found

CAKEPHP 4.4.17

**Comment by cnizzardini** [comment]
Try changing your version constraint to `^1.7` maybe? If you are still getting this error when you can confirm you are on the latest 1.x version I will help out.

**Comment by shaan100** [comment]
yap! its working now, thanks a lot friend
