### ISSUE TITLE
Cannot make controller working

### ISSUE THREAD

**Issue by rudy1976s** [cnizzardini/cakephp-swagger-bake#534]
We have an application based on plugins. We followed the guide and creating a dedicated swagger_bake.php located in the plugin config folder. Here there is the sample code : 

```php
return [
    'SwaggerBake' => [
        'prefix' => '/api-blog',
        'yml' => '/vendor/acme/blog/config/swagger.yml',
        'json' => '/vendor/acme/blog/webroot/swagger.json',
        'webPath' => '/acme/blog/swagger.json',
        'hotReload' => Configure::read('debug'),
        'jsonOptions' => JSON_PRETTY_PRINT,
        'editActionMethods' => ['PATCH'],
        'requestAccepts' => [
            'application/json',
            'application/x-www-form-urlencoded',
            'application/xml',
        ],
        'responseContentTypes' => [
            'application/json',
            'application/xml',
            'application/hal+json',
            'application/json+ld'
        ],
        'docType' => 'swagger',
        'exceptionSchema' => 'Exception',
        'namespaces' => [
            'controllers' => ['\Acme\\Blog\\'],
            'entities' => ['\Acme\\Blog\\'],
            'tables' => ['\Acme\\Blog\\Model\\Table']
        ],
    ]
];
```

we have set up the XMl as follows :

`
openapi: "3.0.0"
info:
  version: 2.5.*
  title: Acme/Blog Api
  description: |
    Acme CMS Blog API
  license:
    name: MIT License
paths:
  '/api-blog/posts/':
    get:
      summary: Index method
      description: 'This shows using the definitions from YML instead of reading from your cake routes and models.
        YML definitions take precedence over cake routes and models.'
      tags:
        - Posts
      operationId: 'posts:index'
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                type: string
      deprecated: false
components:
  securitySchemes:
    ApiKey:
      description: See `/examples/api-key-example` for demo/example.
      type: apiKey
      in: header
      name: API-KEY
  schemas:
    Exception:
      type: object
      properties:
        code:
          type: integer
          example: 500
        url:
          type: string
          example: /url/path
        message:
          type: string
          example: Internal Error
      xml:
        name: response
    OperationResult:
      type: object
      properties:
        result:
          type: boolean
        message:
          type: string
      xml:
        name: response
    Posts:
      type: array
      items:
        $ref: '#/components/schemas/Post'
    Post:
      description: 'Post object'
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          example: 'countries'
`

We have generated the json with the appropriate command.

We have generated routes for the controller we need to manage as follows :

`
$routes->scope('/api-blog', function (RouteBuilder $builder) {
    (new AutoRouter($builder, new ResourceScanner('Acme\Blog')))->buildResources();

    $builder->setExtensions(['json','xml']);

    $builder->connect('/', [
        'plugin' => 'Acme/Blog', 'controller' => 'Swagger', 'action' => 'index'
    ]);
    $builder->connect('/contexts/*', [
        'plugin' => 'MixerApi/JsonLdView', 'controller' => 'JsonLd', 'action' => 'contexts'
    ]);
    $builder->connect('/vocab', [
        'plugin' => 'MixerApi/JsonLdView', 'controller' => 'JsonLd', 'action' => 'vocab'
    ]);
    $builder->plugin('Acme/Blog', ['path' => '/'], function ($routes) {
        $routes->resources('Posts', [
            'only' => ['view','index'],
        ]);
        $routes->fallbacks();
    });
});

`

Then we have created a controller with only two actions as mapped in the routes :

`
declare(strict_types=1);

namespace Acme\Blog\Controller;

use Acme\Blog\Model\Entity\Post;
use Acme\Blog\Model\Table\PostsTable;
use Cake\Datasource\Exception\RecordNotFoundException;
use Cake\Http\Exception\MethodNotAllowedException;
use MixerApi\Crud\Interfaces\ReadInterface;
use MixerApi\Crud\Interfaces\SearchInterface;
use SwaggerBake\Lib\Attribute\OpenApiPaginator;
use SwaggerBake\Lib\Extension\CakeSearch\Attribute\OpenApiSearch;

/**
 * Posts Controller
 *
 * @property PostsTable $Posts
 * @method Post[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class PostsController extends AppController
{
    public function initialize(): void
    {
        parent::initialize();
        $this->loadComponent('Search.Search', [
            'actions' => ['index'],
        ]);
    }
    /**
     * Posts Collection
     *
     * This example uses mixerapi/crud.
     *
     * @param SearchInterface $search
     * @return void
     * @throws MethodNotAllowedException
     */
    #[OpenApiPaginator]
    #[OpenApiSearch(tableClass:PostsTable::class)]
    public function index(SearchInterface $search): void
    {
        $this->set('data', $this->paginate($search->query($this)));
    }

    /**
     * Post Resource
     *
     * This example uses mixerapi/crud.
     *
     * @param ReadInterface $read
     * @return void
     * @throws RecordNotFoundException
     * @throws MethodNotAllowedException
     */
    public function view(ReadInterface $read): void
    {
        $this->set('data', $read->read($this));
    }
}

`

The swagger pages is visible,  but actually the controller is always asking for view template missing , while it should not do, because we should dealing with restful routes. ( the base controller has request handler component loaded )
I think we miss something but after several trying we are unable to come though.
We tried to download and run the mixerapi project ( to check something working) but the docker is not working ( I have opened a ticket for that yesterday ).
I know this topic is complicated , but we are stuck, could you please help us understanding what is wrong with our implementation ?

Thank you in advance

Rudy

**Comment by cnizzardini** [comment]
When you say the swagger page is loading. Are the routes you expect to be there appearing?

**Comment by cnizzardini** [comment]
Closing due to lack of feedback.
