### ISSUE TITLE
Missing schema - Cakephp 5 with Plugins

### ISSUE THREAD

**Issue by ProgTiger** [cnizzardini/cakephp-swagger-bake#550]
**Describe the bug**
Im building a modular API with Cakephp and want to document it with cakephp-swagger-bake. The modules will be created as plugins. Each module has its own database (configured in app_local.php - here: pluginBookmarks).

**To Reproduce**
1. Configure a new database and disable the "default" in app_local.php:
2. Create the plugin e.g.
```Bash
bin/cake bake plugin Bookmarks
```
4. setup a router; controller; model; etc. in the plugin (using cake magic tools)
5. follow the setup guide: https://github.com/cnizzardini/cakephp-swagger-bake/tree/master?tab=readme-ov-file#multiple-instances-of-swagger-bake and creating an own Controller
6. register the Plugin and the SwaggerController in config/route.php
```Php
    $routes->scope('/api/v1', function (RouteBuilder $builder): void {
        $builder->connect('/swagger-bookmarks', ['plugin' => 'Bookmarks', 'controller' => 'Swagger', 'action' => 'index']);
        $builder->loadPlugin('Bookmarks');
    });
```
8. configure swagger_bake.php to use the connectionName of the database
```Php
return [
    'SwaggerBake' => [
        'prefix' => '/api/v1/bookmarks',
        'yml' => '/plugins/Bookmarks/config/swagger.yml',
        'json' => '/webroot/swagger-bookmarks.json',
        'webPath' => '/swagger-bookmarks.json',
        'hotReload' => Configure::read('debug'),
        'jsonOptions' => Configure::read('debug') ? JSON_PRETTY_PRINT : JSON_UNESCAPED_UNICODE,
        'connectionName' => 'pluginBookmarks',
        'namespaces' => [
            'controllers' => ['\Bookmarks\\'],
            'entities' => ['\Bookmarks\\'],
            'tables' => ['\Bookmarks\\']
        ],
```
9. execute swagger models:
```
bin/cake swagger models --config Bookmarks.swagger_bake
```
10. check output (debug was added manual)
```
bin/cake swagger models --config Bookmarks.swagger_bake
-------------------------------------------------------------------------------
| SwaggerBake is checking your models...
-------------------------------------------------------------------------------
ROOT\vendor\cnizzardini\cakephp-swagger-bake\src\Lib\Model\ModelScanner.php (line 69)
########## DEBUG ##########
object(Cake\ORM\Table) id:0 {
  'registryAlias' => 'Links'
  'table' => 'links'
  'alias' => 'Links'
  'entityClass' => 'Cake\ORM\Entity'
  'associations' => []
  'behaviors' => []
  'defaultConnection' => 'default'
  'connectionName' => 'default'
}
###########################
- Entity
+-----------+-----------+--------------+---------+-------------+-----------------+--------+
| Attribute | Data Type | Swagger Type | Default | Primary Key | Mass Assignment | Hidden |
+-----------+-----------+--------------+---------+-------------+-----------------+--------+
| id        | uuid      | string       |         | Y           | Y               |        |
| user_id   | uuid      | string       |         |             | Y               |        |
| url       | string    | string       |         |             | Y               |        |
| created   | datetime  | string       |         |             | Y               |        |
+-----------+-----------+--------------+---------+-------------+-----------------+--------+
```

**Expected behavior**
- I would expect that the connectionName would be "pluginBookmarks" (as in the configuration) and the created schema would be "Links" instat of "Entity".
- The schema would appear in the swagger documentation

**Attachments**
as above.

**Version and Platform (please complete the following information):**
 - CakePHP: 5.0.8
 - cakephp-swagger-bake: v3.0.3

**Additional context**
All functions can be called in swagger ui; it seams there is "just" the missing schema.

**Comment by ProgTiger** [comment]
Please find my merge request as an idea to solve the problem: #551
In my tests it solves the problem:

```
-------------------------------------------------------------------------------
| SwaggerBake is checking your models...
-------------------------------------------------------------------------------
- Link
+-----------+-----------+--------------+---------+-------------+-----------------+--------+
| Attribute | Data Type | Swagger Type | Default | Primary Key | Mass Assignment | Hidden |
+-----------+-----------+--------------+---------+-------------+-----------------+--------+
| id        | uuid      | string       |         | Y           |                 |        |
| user_id   | uuid      | string       |         |             |                 |        |
| url       | string    | string       |         |             | Y               |        |
| created   | datetime  | string       |         |             | Y               |        |
+-----------+-----------+--------------+---------+-------------+-----------------+--------+
```

**Comment by cnizzardini** [comment]
I'll take a look. I haven't had a need for something like this as I do one db per project, even if it has many plugins. One thing to note as adding test coverage for code changes.

**Comment by ProgTiger** [comment]
Thank you for the information and your time. I'm look forward to hear more about this topic.

**Comment by cnizzardini** [comment]
Did you read this: https://github.com/cnizzardini/cakephp-swagger-bake?tab=readme-ov-file#multiple-instances-of-swagger-bake

It doesn't solve your exact need, but I think the remainder could be solved by adding a `database` to the config. This would assume each API has its own API.

**Comment by ProgTiger** [comment]
read it, loved it, implemented it :-)
This is what I did. Created a plugin for each "independent logical cluster of my api" and create an own instance of swagger (with an own swagger-controller) for it. 
I know that this creates an own API for each plugin/"independent logical cluster of my api".
In addition I created a DB-config in app_local.php and use a DB per plugin.
