### ISSUE TITLE
When using plugin with / in the name, plugin paths are skipped

### ISSUE THREAD

**Issue by segy** [cnizzardini/cakephp-swagger-bake#552]
**Describe the bug**
When using plugin with `/` in the name, plugin paths are skipped. The reason is, that the `RouteDecorator` uses the plugin name to build FQN without changing to to backslash.

**To Reproduce**
1. Use plugin with name containing `/`

**Expected behavior**
Endpoints from the plugin appear in the swagger.

**Attachments**
-

**Version and Platform (please complete the following information):**
 - OS/Platform: [e.g. Linux]
 - CakePHP: 5.0.9
 - SwaggerBake Version: v3.0.3  

**Additional context**
-

**Comment by cnizzardini** [comment]
Can you provide some sample code to reproduce this?
