### ISSUE TITLE
Unable to set operationId using the OpenApiOperation annotation.

### ISSUE THREAD

**Issue by marcdebus** [cnizzardini/cakephp-swagger-bake#556]
The default output in swagger.json is generated like this:

    get:
      operationId: actors:index:get
      summary: operation title
      description: a description
      tags:
        - Internal API
        - External API
      externalDocs:
        url: https://github.com/cnizzardini/cakephp-swagger-bake
        description: Check out the documentation
        
Using the #[OpenApiOperation(...)] attribute/annotation, you cannot set the operationId. A generation tool like NSwagStudio produces a C# class with errors, as ":" is not allowed in identifiers.

Invalid token ':' in class ....

**Comment by cnizzardini** [comment]
Interesting, as a workaround, have you tried altering the operationId's using event listeners?

https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/docs/events.md

**Comment by marcdebus** [comment]
No, but I'll try that. Thanks.

**Comment by marcdebus** [comment]
It works, thank you!

**Comment by marcdebus** [comment]
It works, thank you!

**Comment by cnizzardini** [comment]
Re-opening to determine if this should be added into the core feature set.

**Comment by cnizzardini** [comment]
What version of the library are you using?

**Comment by marcdebus** [comment]
I’m currently using version 2.5.9 because I’m working with CakePHP 4.x, but I plan to upgrade to version 5 soon.

**Comment by cnizzardini** [comment]
Closing this as the event listener provides an easy work-around.
